apiVersion: apps/v1
kind: Deployment
metadata:
  name: irisdata-deployment
spec:
  selector:
    matchLabels:
      app: irisdata
  replicas: {{ .Params.replicas }}
  template:
    metadata:
      labels:
        app: irisdata
    spec:
      containers:
        - name: irisdata
          image: cskeen/irisdataset:{{ .AppVersion }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: irisdata-config