apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          ports:
            - containerPort: {{ .Params.REDIS_PORT }}
          volumeMounts:
            - name: redis-volume
              mountPath: /bitnami/redis/data
          envFrom:
            - configMapRef:
                name: redis-config
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-pv-claim